spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?allowMultiQueries=true&charset=utf8mb4&serverTimezone=UTC&characterEncoding=utf-8
    username: acmday
    password: acmday
    maxPoolSize: 5
    minPoolSize: 5
    initialPoolSize: 1
  redis:
    host: localhost
